apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: blog-app
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cmt2QDI3MTI=

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: blog-app
spec:
  ports:
    - port: 3306
  selector:
    app: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: blog-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: bloghub
          ports:
            - containerPort: 3306